/*
 * Copyright (C) 2014 The Holodeck B2B Team, Sander Fieten
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.holodeckb2b.common.security;

/**
 * @author Sander Fieten <sander at holodeck-b2b.org>
 * @author Bram Bakx <bram at holodeck-b2b.org>
 */
public interface IEncryptionConfiguration {
    
    /**
     * Gets the Java keystore <i>alias</i> that identifies the X509 certificate that should be used for signing.
     * <p>The current implementation of Holodeck B2B uses Java keystores to store certificates. Two keystores are used 
     * to storing private and public certificates and another for storing CA certificates (the trust store). Depending
     * what this configuration applies to the certificate must exist in either the private (when signing outgoing 
     * messages) or public (when validating incoming messages) keystore.
     * 
     * @return  The alias that identifies the certificate to use for signing.
     */
    public String getKeystoreAlias();
    
    
    /**
     * Gets the password to access the private key hold by the certififcate. Only applies to configurations that are
     * used to encrypt messages.
     * <p>Current implementation of Holodeck B2B requires that result is the password in clear text. Future version may
     * change this to get better secured passwords.
     * 
     * @return  The password to get access to the private key
     */
    public String getCertificatePassword();
    
    
    /**
     * Gets the method of referencing the certificate used for signing. Section 3.2 of the WS-Security X.509 Certificate 
     * Token Profile Version 1.1.1 specification defines the three options that are allowed for referencing the 
     * certificate.
     * <p>NOTE 1: This setting only applies to signature that are generated by Holodeck B2B, i.e. for outgoing messages.
     * When the signature of an incoming message is validated the reference included in the message will be used to look
     * up the certificate regardless of the used reference method. 
     * <p>NOTE 2: When not specified in the P-Mode Holodeck B2B will reference the certificate using its issuer and 
     * serial number (as specified in section 3.2.3 of WS-Sec X.509 CTP).
     * 
     * @return  The method to be used for referencing the certificate, or<br>
     *          <code>null</code> if no method is specified
     */
    public X509ReferenceType getKeyReferenceMethod();
    
    
    /**
     * Gets the symmetric encryption algorithm.
     * 
     * @return The symmetric encryption algorithm to be used,<br>
     *         default is AES-128.
     */
    public String getAlgorithm();
    
    
    /**
     * Gets the key transport settings.
     * 
     * @return An {@link IKeyTransport} object containing the 
     * key transport data.
     */
    public IKeyTransport getKeyTransport();
    
}
